name: bft_calculator
description: "Know your Basic Fitness Test Requirement for GAF"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gaf.png"
  min_sdk_android: 36

flutter:
  uses-material-design: true
  assets: 
    - assets/gaf.png
    - assets/gaf2.jpg
    - assets/gaf3.jpg
    - assets/t1.jpg
    - assets/t2.jpg
    - assets/t3.jpg
    - assets/t4.jpg
    - assets/t5.jpg
